// Items
export const SET_STORY_TYPE = "SET_STORY_TYPE";
export const SET_POSTS = "SET_POSTS";
export const SET_POSTS_LOADING = "SET_POSTS_LOADING";

// Auth
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const SET_ACCOUNTS_DETAILS = "SET_ACCOUNTS_DETAILS";
export const ADD_UPVOTED_POST = "ADD_UPVOTED_POST";
export const CHANGE_SAVED_POSTS = "CHANGE_SAVED_POSTS";